version: '3.9'

services:
   rust_api_db:
     container_name: rust_api_db
     image: postgres:12
     ports:
        - "5432:5432"

     environment:
        - POSTGRES_USER=satyam
        - POSTGRES_PASSWORD=12345
        - POSTGRES_DB=rust_api_database
     volumes:
        - rust_api_data:/var/lib/postgresql/data

volumes: 
  rust_api_data:
